### ISSUE TITLE
Initial Migration Attempt Fails in Foundry v10

### ISSUE THREAD

**Issue by WesWedding** [WesWedding/sta-enhanced#17]
### Foundry VTT Version

10

### What did you do?

Upon loading the game in v10, the check for migrations fails in the Ready hook because the system throws an error on one of the first lines.

### What did you see happen?

The error console shows...

```
Error: Setting Model Validation Errors
[Setting.value]: may not be undefined
    at SchemaField._validateType (commons.js:4098:15)
    at SchemaField.validate (commons.js:3824:37)
    at Setting.validate (commons.js:5492:35)
    at new DataModel (commons.js:5269:26)
    at new Document (commons.js:5811:3)
    at new BaseSetting (commons.js:9832:3)
    at new ClientDocumentMixin (foundry.js:13053:5)
    at new Setting (foundry.js:21323:1)
    at ClientSettings.get (foundry.js:2815:21)
    at Object.fn (ready.mjs:13:44)
onError @ foundry.js:747
#call @ foundry.js:728
callAll @ foundry.js:681
setupGame @ foundry.js:7952
await in setupGame (async)
_initializeGameView @ foundry.js:8999
_initializeView @ foundry.js:8975
initialize @ foundry.js:7825
await in initialize (async)
window.addEventListener.once @ foundry.js:79752
```

### What did you expect to see?

The first time the Plugin runs, it will check for migrations and attempt to run them.  It did not.

**Comment by WesWedding** [comment]
This is triggered by the line

`const currentVersion = game.settings.get('sta-enhanced', 'worldSchemaVersion');`

**Comment by WesWedding** [comment]
This is medium priority issue because there were zero users that needed to migrate on v10 to begin with (the migration predates any public releases).  That said, an error being thrown in the background every time someone runs this in Core v10 isn't great!

**Comment by WesWedding** [comment]
v10 support is being dropped with the release of the Reputation Roll functionality.
