### ISSUE TITLE
Enhanced Sheet Broken after latest System Updates

### ISSUE THREAD

**Issue by WesWedding** [WesWedding/sta-enhanced#26]
### Foundry VTT Version

12

### What did you do?

Opened the enhanced sheet and switched to the Reputation tab.

### What did you see happen?

The reputation tab is blank.  The error log reports

```
Error: An error occurred while rendering STACharacterEnhancedSheet 26. localizedValues is not defined
    at Hooks.onError (foundry.js:654:24)
    at foundry.js:5794:13
```

### What did you expect to see?

The usual rep stuff; a reputation track.

**Comment by WesWedding** [comment]
All of the sheet behavior is busted, actually.
